import React, { createContext, useContext, useState, useCallback } from "react";

const ru = {
  loading: "Загрузка...",
  cancel: "Отмена",
  save: "Сохранить",
  delete: "Удалить",
  close: "Закрыть",
  search: "Поиск",
  error: "Ошибка",

  authTitle: "Q3 AI",
  authSubtitle: "",
  login: "Вход",
  register: "Регистрация",
  email: "Электронная почта",
  emailPlaceholder: "Введите email",
  password: "Пароль",
  passwordPlaceholder: "Введите пароль",
  confirmPassword: "Подтвердите пароль",
  confirmPasswordPlaceholder: "Повторите пароль",
  passwordHint: "Мин. 8 символов, буквы + цифры",
  loginBtn: "Войти",
  checkEmail: "Проверить email",
  registerBtn: "Зарегистрироваться",
  changeEmail: "\u2190 Изменить email",
  authHint: "Регистрация доступна только для авторизованных администратором email-адресов.",
  emailNotFound: "Email не авторизован администратором. Обратитесь к администратору для получения доступа.",
  emailAlreadyRegistered: "Аккаунт уже зарегистрирован. Используйте вкладку \u00abВход\u00bb.",
  enterEmail: "Введите email",
  enterPassword: "Введите пароль",
  passwordsNoMatch: "Пароли не совпадают",
  passwordTooShort: "Пароль должен быть не менее 8 символов",
  passwordNeedLetter: "Пароль должен содержать хотя бы одну букву",
  passwordNeedDigit: "Пароль должен содержать хотя бы одну цифру",

  collapse: "Свернуть",
  expand: "Развернуть",
  newChat: "Новый чат",
  searchChats: "Поиск в чатах",
  database: "База данных",
  chats: "Чаты",
  profile: "Профиль",
  adminPanel: "Админ панель",
  settings: "Настройки",
  logout: "Выйти",

  emptyTitle: "Q3 AI",
  emptySubtitle: "",
  generating: "Генерация...",
  aiUsingTool: "ИИ использует инструмент:",
  ollamaConnected: "Ollama подключена",
  ollamaDisconnected: "Ollama не подключена",
  ollamaChecking: "Проверка...",
  ollamaOffline: "Ollama offline",
  exportChat: "Экспорт чата (Markdown)",
  exportPdf: "Экспорт в PDF",
  lightTheme: "Светлая тема",
  darkTheme: "Тёмная тема",

  sugCompare: "Сравни два документа",
  sugCompareDesc: "Анализ изменений между договорами",
  sugSort: "Рассортируй файлы",
  sugSortDesc: "Организация документов по категориям",
  sugAnalyze: "Проанализируй договор",
  sugAnalyzeDesc: "Ключевые условия и суммы",
  sugSearch: "Найди документ",
  sugSearchDesc: "Поиск по базе данных компании",

  shortcutNewChat: "Новый чат",
  shortcutSearch: "Поиск",
  shortcutClose: "Закрыть",

  inputPlaceholder: "Спросите что-нибудь...",
  preview: "Предпросмотр",
  previewFile: "Предпросмотр файла",

  thinking: "Думает",
  thought: "Думал",
  sec: "сек",
  min: "мин",
  copiedCode: "Скопировано!",
  copyCode: "Копировать",

  deleteChat: "Удалить чат?",
  deleteChatConfirm: "Это действие нельзя отменить. Все сообщения будут удалены.",

  migrationTitle: "Обнаружены локальные чаты",
  migrationDesc: "Найдены чаты в локальном хранилище браузера. Хотите импортировать их в вашу учётную запись?",
  importBtn: "Импортировать",
  importing: "Импорт...",
  skip: "Пропустить",

  adminTitle: "Панель администратора",
  users: "Пользователи",
  backups: "Резервные копии",
  addUser: "Добавить пользователя",
  editUser: "Редактировать пользователя",
  deleteUser: "Удалить пользователя?",
  deleteUserConfirm: "Все данные пользователя (чаты, сообщения, документы) будут удалены.",
  lastName: "Фамилия",
  firstName: "Имя",
  patronymic: "Отчество",
  position: "Должность",
  status: "Статус",
  actions: "Действия",
  admin: "Админ",
  active: "Активен",
  inactive: "Неактивен",
  pending: "Ожидает",
  noUsers: "Нет пользователей",
  emailFirstLastRequired: "Email, Имя и Фамилия обязательны",
  saving: "Сохранение...",
  add: "Добавить",
  createBackup: "Создать копию",
  creating: "Создание...",
  backupNotePlaceholder: "Примечание (необязательно)",
  date: "Дата",
  size: "Размер",
  note: "Примечание",
  author: "Автор",
  noBackups: "Нет резервных копий",
  restoreConfirm: "Восстановить базу данных из этой резервной копии? Текущие данные будут перезаписаны.",
  deleteBackupConfirm: "Удалить эту резервную копию?",
  fio: "ФИО",

  settingsTitle: "Настройки",
  model: "Модель",
  noModels: "Нет моделей",
  temperature: "Температура",
  tempPrecise: "Точный (0)",
  tempCreative: "Креативный (2)",
  thinkingMode: "Режим размышлений",
  thinkingOn: "Thinking Mode (размышление)",
  thinkingOff: "Non-Thinking (быстрый)",
  contextWindow: "Контекст (токены)",
  contextTokens: "токенов",
  lessMemory: "Меньше памяти",
  moreContext: "Больше контекста",
  language: "Язык",
  theme: "Тема оформления",
  themeDark: "Тёмная тема",
  themeLight: "Светлая тема",
  hotkeys: "Горячие клавиши",
  hotkeyNewChat: "Новый чат",
  hotkeySearch: "Поиск",
  hotkeySend: "Отправить сообщение",
  hotkeyNewLine: "Новая строка",
  hotkeyClose: "Закрыть окно",

  profileTitle: "Профиль",
  personalData: "Личные данные",
  personalDataNote: "Для изменения личных данных обратитесь к администратору.",
  changePassword: "Сменить пароль",
  currentPassword: "Текущий пароль",
  newPassword: "Новый пароль",
  confirmNewPassword: "Подтвердите новый пароль",
  enterCurrentPassword: "Введите текущий пароль",
  enterNewPassword: "Введите новый пароль",
  repeatNewPassword: "Повторите новый пароль",
  passwordTooShortProfile: "Новый пароль должен быть не менее 4 символов",
  passwordChanged: "Пароль успешно изменён!",

  searchMessages: "Поиск по сообщениям...",
  searching: "Поиск...",
  nothingFound: "Ничего не найдено",
  searchHint: "Введите текст для поиска по всем сообщениям",
  you: "Вы",
  ai: "ИИ",
  searchTabChats: "По чатам",
  searchTabSmart: "Умный поиск",
  smartSearchPlaceholder: "Поиск по смыслу в документах...",
  smartSearchHint: "Семантический поиск находит документы по смыслу, а не по точному совпадению слов.",
  smartSearchExample: "Пример: \"ответственность за задержку\" найдёт пункты о штрафах и неустойках",
  typeHybrid: "Гибридный",
  typeSemantic: "Семантический",
  matchHybrid: "Гибрид",
  matchSemantic: "Семантика",
  matchKeyword: "Ключевые слова",

  knowledgeBase: "База знаний",
  uploadFile: "Загрузить файл",
  createFolder: "Создать папку",
  moveToFolder: "Переместить в папку",
  rootFolder: "Корневая папка",
  folderName: "Название папки",
  noDocuments: "Нет документов",
  dragDropHint: "Перетащите файлы сюда",
  sortNewest: "Новые",
  sortOldest: "Старые",

  rename: "Переименовать",
  renameChat: "Переименовать чат",
  open: "Открыть",
  copy: "Копировать",
  edit: "Редактировать",
  activate: "Активировать",
  deactivate: "Деактивировать",
  restore: "Восстановить",
  deleteUserConfirmMsg: "Вы уверены, что хотите удалить пользователя",
  previewTruncated: "(показано первые 1000 символов)",

  compareAskFiles: "Пожалуйста, прикрепите два файла для сравнения и нажмите Enter. Вы также можете указать, на что обратить внимание при сравнении, или просто нажмите Enter для общего сравнения.",
  compareDefaultPrompt: "ЗАДАНИЕ: Сравни ФАЙЛ 1 и ФАЙЛ 2 между собой. Это ДВА РАЗНЫХ документа, разделённых маркерами '=========='. Подробно выдели ВСЕ различия и сходства между ними, представь результат в виде таблицы. ВАЖНО: заполняй КАЖДУЮ ячейку таблицы — ни одна не должна быть пустой. Если данные отсутствуют — пиши '—' или 'Нет данных'. Генерируй таблицу ПОЛНОСТЬЮ, не обрывай на середине.",
  sortDefaultPrompt: "ЗАДАНИЕ: Рассортируй прикреплённые документы по категориям (договоры, акты, счета, письма, приказы и т.д.). Для каждого документа укажи: название, тип документа, краткое описание содержания. Представь результат в виде таблицы.",
  analyzeDefaultPrompt: "ЗАДАНИЕ: Проведи детальный анализ прикреплённого документа. Извлеки: стороны, предмет, ключевые условия, суммы, сроки, штрафы, особые условия. Представь структурированный обзор.",

  sortAskFiles: "Прикрепите файлы для сортировки и нажмите Enter. Я автоматически определю тип каждого документа, создам папки по категориям и загружу всё в базу знаний.",
  analyzeAskFile: "Прикрепите документ для анализа и нажмите Enter. Я извлеку ключевые условия, суммы, даты, стороны и представлю структурированный обзор.",
  searchAskQuery: "Опишите, какой документ вы ищете, и я найду его в базе знаний. Например: \"договор с ООО Альфа\" или \"акт за март 2026\".",

  sortDone: "Сортировка завершена!",
  sortTotalFiles: "Файлов обработано",
  sortTotalCategories: "Категорий создано",
  sortFolder: "Папка в базе знаний",
  sortErrors: "Ошибки",
  sortOpenKB: "Откройте **Базу знаний** в боковом меню, чтобы увидеть отсортированные документы.",
  sortError: "Ошибка сортировки",

  errorFetch: "Ошибка: Failed to fetch. Убедитесь, что Ollama запущен.",
  errorOllama: "Ошибка: Ollama не запущена. Запустите `ollama serve`.",
};

const en = {
  loading: "Loading...",
  cancel: "Cancel",
  save: "Save",
  delete: "Delete",
  close: "Close",
  search: "Search",
  error: "Error",

  authTitle: "Q3 AI",
  authSubtitle: "",
  login: "Login",
  register: "Register",
  email: "Email",
  emailPlaceholder: "Enter email",
  password: "Password",
  passwordPlaceholder: "Enter password",
  confirmPassword: "Confirm password",
  confirmPasswordPlaceholder: "Repeat password",
  passwordHint: "Min 8 chars, letters + digits",
  loginBtn: "Sign In",
  checkEmail: "Check email",
  registerBtn: "Register",
  changeEmail: "\u2190 Change email",
  authHint: "Registration is only available for admin-authorized email addresses.",
  emailNotFound: "Email not authorized by admin. Contact your administrator for access.",
  emailAlreadyRegistered: "Account already registered. Use the Login tab.",
  enterEmail: "Enter email",
  enterPassword: "Enter password",
  passwordsNoMatch: "Passwords don't match",
  passwordTooShort: "Password must be at least 8 characters",
  passwordNeedLetter: "Password must contain at least one letter",
  passwordNeedDigit: "Password must contain at least one digit",

  collapse: "Collapse",
  expand: "Expand",
  newChat: "New Chat",
  searchChats: "Search chats",
  database: "Database",
  chats: "Chats",
  profile: "Profile",
  adminPanel: "Admin Panel",
  settings: "Settings",
  logout: "Log Out",

  emptyTitle: "Q3 AI",
  emptySubtitle: "",
  generating: "Generating...",
  aiUsingTool: "AI is using tool:",
  ollamaConnected: "Ollama connected",
  ollamaDisconnected: "Ollama disconnected",
  ollamaChecking: "Checking...",
  ollamaOffline: "Ollama offline",
  exportChat: "Export chat (Markdown)",
  exportPdf: "Export to PDF",
  lightTheme: "Light theme",
  darkTheme: "Dark theme",

  sugCompare: "Compare two documents",
  sugCompareDesc: "Analyze changes between contracts",
  sugSort: "Sort files",
  sugSortDesc: "Organize documents by categories",
  sugAnalyze: "Analyze a contract",
  sugAnalyzeDesc: "Key terms and amounts",
  sugSearch: "Find a document",
  sugSearchDesc: "Search the company database",

  shortcutNewChat: "New chat",
  shortcutSearch: "Search",
  shortcutClose: "Close",

  inputPlaceholder: "Ask anything...",
  preview: "Preview",
  previewFile: "File preview",

  thinking: "Thinking",
  thought: "Thought",
  sec: "sec",
  min: "min",
  copiedCode: "Copied!",
  copyCode: "Copy",

  deleteChat: "Delete chat?",
  deleteChatConfirm: "This action cannot be undone. All messages will be deleted.",

  migrationTitle: "Local chats detected",
  migrationDesc: "Chats found in browser storage. Import them to your account?",
  importBtn: "Import",
  importing: "Importing...",
  skip: "Skip",

  adminTitle: "Admin Panel",
  users: "Users",
  backups: "Backups",
  addUser: "Add user",
  editUser: "Edit user",
  deleteUser: "Delete user?",
  deleteUserConfirm: "All user data (chats, messages, documents) will be deleted.",
  lastName: "Last name",
  firstName: "First name",
  patronymic: "Patronymic",
  position: "Position",
  status: "Status",
  actions: "Actions",
  admin: "Admin",
  active: "Active",
  inactive: "Inactive",
  pending: "Pending",
  noUsers: "No users",
  emailFirstLastRequired: "Email, First name, and Last name are required",
  saving: "Saving...",
  add: "Add",
  createBackup: "Create backup",
  creating: "Creating...",
  backupNotePlaceholder: "Note (optional)",
  date: "Date",
  size: "Size",
  note: "Note",
  author: "Author",
  noBackups: "No backups",
  restoreConfirm: "Restore database from this backup? Current data will be overwritten.",
  deleteBackupConfirm: "Delete this backup?",
  fio: "Full Name",

  settingsTitle: "Settings",
  model: "Model",
  noModels: "No models",
  temperature: "Temperature",
  tempPrecise: "Precise (0)",
  tempCreative: "Creative (2)",
  thinkingMode: "Thinking mode",
  thinkingOn: "Thinking Mode (reasoning)",
  thinkingOff: "Non-Thinking (fast)",
  contextWindow: "Context (tokens)",
  contextTokens: "tokens",
  lessMemory: "Less memory",
  moreContext: "More context",
  language: "Language",
  theme: "Theme",
  themeDark: "Dark theme",
  themeLight: "Light theme",
  hotkeys: "Keyboard shortcuts",
  hotkeyNewChat: "New chat",
  hotkeySearch: "Search",
  hotkeySend: "Send message",
  hotkeyNewLine: "New line",
  hotkeyClose: "Close window",

  profileTitle: "Profile",
  personalData: "Personal data",
  personalDataNote: "Contact your administrator to change personal data.",
  changePassword: "Change password",
  currentPassword: "Current password",
  newPassword: "New password",
  confirmNewPassword: "Confirm new password",
  enterCurrentPassword: "Enter current password",
  enterNewPassword: "Enter new password",
  repeatNewPassword: "Repeat new password",
  passwordTooShortProfile: "New password must be at least 4 characters",
  passwordChanged: "Password changed successfully!",

  searchMessages: "Search messages...",
  searching: "Searching...",
  nothingFound: "Nothing found",
  searchHint: "Enter text to search all messages",
  you: "You",
  ai: "AI",
  searchTabChats: "Chats",
  searchTabSmart: "Smart Search",
  smartSearchPlaceholder: "Semantic search in documents...",
  smartSearchHint: "Semantic search finds documents by meaning, not exact word match.",
  smartSearchExample: "Example: \"liability for delay\" will find clauses about penalties",
  typeHybrid: "Hybrid",
  typeSemantic: "Semantic",
  matchHybrid: "Hybrid",
  matchSemantic: "Semantic",
  matchKeyword: "Keywords",

  knowledgeBase: "Knowledge Base",
  uploadFile: "Upload file",
  createFolder: "Create folder",
  moveToFolder: "Move to folder",
  rootFolder: "Root folder",
  folderName: "Folder name",
  noDocuments: "No documents",
  dragDropHint: "Drag files here",
  sortNewest: "Newest",
  sortOldest: "Oldest",

  rename: "Rename",
  renameChat: "Rename chat",
  open: "Open",
  copy: "Copy",
  edit: "Edit",
  activate: "Activate",
  deactivate: "Deactivate",
  restore: "Restore",
  deleteUserConfirmMsg: "Are you sure you want to delete user",
  previewTruncated: "(showing first 1000 characters)",

  compareAskFiles: "Please attach two files for comparison and press Enter. You can also specify what to focus on, or just press Enter for a general comparison.",
  compareDefaultPrompt: "TASK: Compare FILE 1 and FILE 2 with each other. These are TWO DIFFERENT documents separated by '==========' markers. List ALL differences and similarities between them in a table. IMPORTANT: fill EVERY cell of the table — no cell should be empty. If data is missing — write '—' or 'N/A'. Generate the FULL table, do not cut off mid-way.",
  sortDefaultPrompt: "TASK: Sort the attached documents by category (contracts, acts, invoices, letters, orders, etc.). For each document specify: name, document type, brief description. Present the result in a table.",
  analyzeDefaultPrompt: "TASK: Perform a detailed analysis of the attached document. Extract: parties, subject, key terms, amounts, deadlines, penalties, special conditions. Present a structured overview.",

  sortAskFiles: "Attach files for sorting and press Enter. I will automatically detect each document type, create category folders, and upload everything to the knowledge base.",
  analyzeAskFile: "Attach a document for analysis and press Enter. I will extract key terms, amounts, dates, parties and present a structured overview.",
  searchAskQuery: "Describe what document you're looking for and I'll find it in the knowledge base. For example: \"contract with Alpha LLC\" or \"March 2026 report\".",

  sortDone: "Sorting complete!",
  sortTotalFiles: "Files processed",
  sortTotalCategories: "Categories created",
  sortFolder: "Knowledge base folder",
  sortErrors: "Errors",
  sortOpenKB: "Open **Knowledge Base** in the sidebar to view sorted documents.",
  sortError: "Sorting error",

  errorFetch: "Error: Failed to fetch. Make sure Ollama is running.",
  errorOllama: "Error: Ollama is not running. Run `ollama serve`.",
};

const locales = { ru, en };

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("qwen3_lang") || "ru");

  const changeLang = useCallback((newLang) => {
    setLang(newLang);
    localStorage.setItem("qwen3_lang", newLang);
  }, []);

  const t = useCallback(
    (key) => locales[lang]?.[key] ?? locales.ru[key] ?? key,
    [lang]
  );

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
